In [0]:
import numpy as np

### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
arr = np.random.randint(1, 51, size=(10))
print('Array original: ', arr)

media = np.median(arr)
print('Média: ', media)

desvio = np.std(arr)
print('Desvio padrão: ', desvio)

Array original:  [ 6  1 16 40  6 42 43 12 38  1]
Média:  14.0
Desvio padrão:  17.11286066091815


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
arr = np.random.rand(10)
print('Array original: ', arr)

arr[arr <= 0.5] = np.sqrt(arr[arr <= 0.5])
print('Array com raiz quadrada: ', arr)

Array original:  [0.3357558  0.7684733  0.22689769 0.44400074 0.44266494 0.01858069
 0.00788319 0.34498847 0.53230772 0.97203414]
Array com raiz quadrada:  [0.57944439 0.7684733  0.47633779 0.66633381 0.6653307  0.13631099
 0.08878733 0.58735719 0.53230772 0.97203414]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)
print('Matriz original: ', matriz)

matriz_2d = np.max(matriz, axis=1)

print('Matriz 2D: ', matriz_2d)


Matriz original:  [[[0.68572548 0.98343862 0.79811464]
  [0.80779745 0.19346944 0.37250407]
  [0.55206938 0.8114774  0.39027246]]

 [[0.61227033 0.44981995 0.82892529]
  [0.66512291 0.18890981 0.65416691]
  [0.39296629 0.40269694 0.60614214]]

 [[0.27362247 0.49886247 0.59009181]
  [0.08047082 0.22292283 0.37919254]
  [0.95737299 0.27972703 0.79702235]]]
Matriz 2D:  [[0.80779745 0.98343862 0.79811464]
 [0.66512291 0.44981995 0.82892529]
 [0.95737299 0.49886247 0.79702235]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5,5)
print('Matriz original: ', matriz)

media = np.median(matriz, axis=1)
print('Media: ', media)

matriz_nova = matriz - media[:, np.newaxis]
print('Matriz nova: ', matriz_nova)

Matriz original:  [[0.54270187 0.07910427 0.41685204 0.33717741 0.46563886]
 [0.32766112 0.19623294 0.12241853 0.22616829 0.42427678]
 [0.79920583 0.38011146 0.15100203 0.45801569 0.16126589]
 [0.25893783 0.36304933 0.73791673 0.59757322 0.55083376]
 [0.72668259 0.41156078 0.99707508 0.45564784 0.97858799]]
Media:  [0.41685204 0.22616829 0.38011146 0.55083376 0.72668259]
Matriz nova:  [[ 0.12584984 -0.33774777  0.         -0.07967462  0.04878682]
 [ 0.10149283 -0.02993535 -0.10374976  0.          0.19810849]
 [ 0.41909437  0.         -0.22910943  0.07790423 -0.21884557]
 [-0.29189592 -0.18778442  0.18708297  0.04673947  0.        ]
 [ 0.         -0.3151218   0.27039249 -0.27103474  0.2519054 ]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4,4)
print('Matriz original: ', matriz)

diagonal_principal = np.diag(matriz)
print('Diagonal principal: ', diagonal_principal)

diagonal_secundaria = np.diag(np.fliplr(matriz))
print('Diagonal secundaria: ', diagonal_secundaria)

media_principal = np.mean(diagonal_principal)
media_secundaria = np.mean(diagonal_secundaria)

print('Média da diagonal principal: ', media_principal)
print('Média da diagonal secundaria: ', media_secundaria)

desvio_principal = np.std(diagonal_principal)
desvio_secundaria = np.std(diagonal_secundaria)

print('Desvio padrão principal: ', desvio_principal)
print('Desvio padrão secundaria: ', desvio_secundaria)

Matriz original:  [[0.71353147 0.1620903  0.28046904 0.3253537 ]
 [0.46547035 0.65709842 0.97944797 0.86001634]
 [0.69836299 0.09682098 0.35607597 0.10069395]
 [0.50009467 0.9495641  0.14553834 0.03064688]]
Diagonal principal:  [0.71353147 0.65709842 0.35607597 0.03064688]
Diagonal secundaria:  [0.3253537  0.97944797 0.09682098 0.50009467]
Média da diagonal principal:  0.4393381825396132
Média da diagonal secundaria:  0.47542932888208095
Desvio padrão principal:  0.2722878338255247
Desvio padrão secundaria:  0.3242337682840126
